[language-server.expert]
command = "expert"
args = ["--stdio"]

[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "nix"
formatter = { command = "nixfmt", args = ["-"] }

[[language]]
name = "rust"
formatter = { command = "rustfmt" }

[[language]]
name = "elixir"
language-servers = ["expert"]
formatter = { command = "mix", args = ["format", "-"] }

[[language]]
name = "ocaml"
language-servers = ["ocamllsp"]
auto-format = true
formatter = { command = "ocamlformat", args = ["--enable-outside-detected-project", "--name", "%{buffer_name}", "-"] }

[[language]]
name = "ocaml-interface"
language-servers = ["ocamllsp"]
auto-format = true
formatter = { command = "ocamlformat", args = ["--enable-outside-detected-project", "--name", "%{buffer_name}", "-"] }

[[language]]
name = "ruby"
language-servers = ["ruby-lsp"]
